package fr.lilone.bingobreed.sniffer.model.breeding

/**
 * Référence statique des succès d'élevage : id → nom / description / points / catégorie /
 * objectifs / enfants. Source : API REST DofusDB (familles Dragodinde / Muldo / Volkorne).
 * Maps codées en dur (cf. [Robes]) : vérifiées à la compilation, sans I/O runtime.
 *
 * ⚠️ FICHIER GÉNÉRÉ depuis le dump DofusDB — ne pas éditer à la main.
 *
 * Deux espaces d'ids distincts : [NAMES]/[DESCRIPTIONS]/[POINTS]/[CATEGORY]/[CHILDREN] indexent
 * les **succès** (champ réseau `mgc.gfsm`), [OBJECTIVES] indexe les **objectifs** (champ `mga.gfsi`).
 */
object AchievementRegistry {

    fun name(achievementId: Int): String? = NAMES[achievementId]
    fun description(achievementId: Int): String? = DESCRIPTIONS[achievementId]
    fun points(achievementId: Int): Int? = POINTS[achievementId]
    fun category(achievementId: Int): AchievementCategory? = CATEGORY[achievementId]
    fun children(achievementId: Int): List<Int> = CHILDREN[achievementId] ?: emptyList()
    fun objectiveText(objectiveId: Int): String? = OBJECTIVES[objectiveId]

    /**
     * Tous les objectifs connus (id → libellé), pour construire des **index inverses** libellé → id
     * (cf. [fr.lilone.bingobreed.breeding.ReproTargets]). Les libellés sont préfixés par la famille
     * (« Muldo … », « Volkorne … ») : indispensable, les noms courts de robe se répètent entre familles.
     */
    val ALL_OBJECTIVES: Map<Int, String> get() = OBJECTIVES

    private val NAMES: Map<Int, String> = mapOf(
        91 to "L'éleveur c'est moi",
        133 to "De génération en génération",
        96 to "Dragodinde : Deuxième génération",
        97 to "Dragodinde : Troisième génération",
        98 to "Dragodinde : Quatrième génération",
        99 to "Dragodinde : Cinquième génération",
        100 to "Dragodinde : Sixième génération",
        101 to "Dragodinde : Septième génération",
        130 to "Dragodinde : Huitième génération",
        131 to "Dragodinde : Neuvième génération",
        132 to "Dragodinde : Dixième génération",
        1488 to "Prélèvement marin",
        1497 to "Générations aquatiques",
        1490 to "Muldo : Deuxième génération",
        1491 to "Muldo : Troisième génération",
        1492 to "Muldo : Quatrième génération",
        1493 to "Muldo : Cinquième génération",
        1494 to "Muldo : Sixième génération",
        1495 to "Muldo : Septième génération",
        1496 to "Muldo : Huitième génération",
        9013 to "Muldo : Neuvième génération",
        9014 to "Muldo : Dixième génération",
        9015 to "Prélèvement cornu",
        95 to "Ce n'est qu'un prélèvement",
        109 to "Allez on pousse !",
        1694 to "Génération V",
        1692 to "Volkorne : Deuxième génération",
        1691 to "Volkorne : Troisième génération",
        1690 to "Volkorne : Quatrième génération",
        1689 to "Volkorne : Cinquième génération",
        1688 to "Volkorne : Sixième génération",
        1687 to "Volkorne : Septième génération",
        1686 to "Volkorne : Huitième génération",
        1685 to "Volkorne : Neuvième génération",
        1684 to "Volkorne : Dixième génération",
        106 to "Matrone",
        107 to "Elle a peut-être trop mangé ?",
        108 to "Sage-femme",
    )

    private val DESCRIPTIONS: Map<Int, String> = mapOf(
        91 to "Obtenir les succès suivants.",
        133 to "Obtenir les Succès suivants.",
        96 to "Obtenir la naissance de toutes les Dragodindes de deuxième génération.",
        97 to "Obtenir la naissance de toutes les Dragodindes de troisième génération.",
        98 to "Obtenir la naissance de toutes les Dragodindes de quatrième génération.",
        99 to "Obtenir la naissance de toutes les Dragodindes de cinquième génération.",
        100 to "Obtenir la naissance de toutes les Dragodindes de sixième génération.",
        101 to "Obtenir la naissance de toutes les Dragodindes de septième génération.",
        130 to "Obtenir la naissance de toutes les Dragodindes de huitième génération.",
        131 to "Obtenir la naissance de toutes les Dragodindes de neuvième génération.",
        132 to "Obtenir la naissance de toutes les Dragodindes de dixième génération.",
        1488 to "Capturer les Muldos.",
        1497 to "Obtenir les Succès suivants.",
        1490 to "Obtenir la naissance de tous les Muldos de deuxième génération.",
        1491 to "Obtenir la naissance de tous les Muldos de troisième génération.",
        1492 to "Obtenir la naissance de tous les Muldos de quatrième génération.",
        1493 to "Obtenir la naissance de tous les Muldos de cinquième génération.",
        1494 to "Obtenir la naissance de tous les Muldos de sixième génération.",
        1495 to "Obtenir la naissance de tous les Muldo de septième génération.",
        1496 to "Obtenir la naissance de tous les Muldos de huitième génération.",
        9013 to "Obtenir la naissance de tous les Muldo de neuvième génération.",
        9014 to "Obtenir la naissance de tous les Muldos de dixième génération.",
        9015 to "Capturer les Volkornes.",
        95 to "Capturer les Dragodindes.",
        109 to "Faire naître 1000 montures.",
        1694 to "Obtenir les Succès suivants.",
        1692 to "Obtenir la naissance de tous les Volkornes de deuxième génération.",
        1691 to "Obtenir la naissance de tous les Volkornes de troisième génération.",
        1690 to "Obtenir la naissance de tous les Volkornes de quatrième génération.",
        1689 to "Obtenir la naissance de tous les Volkornes de cinquième génération.",
        1688 to "Obtenir la naissance de tous les Volkornes de sixième génération.",
        1687 to "Obtenir la naissance de tous les Volkornes de septième génération.",
        1686 to "Obtenir la naissance de tous les Volkornes de huitième génération.",
        1685 to "Obtenir la naissance de tous les Volkornes de neuvième génération.",
        1684 to "Obtenir la naissance de tous les Volkornes de dixième génération.",
        106 to "Faire naître 10 montures.",
        107 to "Faire naître 1 monture.",
        108 to "Faire naître 100 montures.",
    )

    private val POINTS: Map<Int, Int> = mapOf(
        91 to 100,
        133 to 50,
        96 to 10,
        97 to 20,
        98 to 20,
        99 to 30,
        100 to 30,
        101 to 40,
        130 to 40,
        131 to 50,
        132 to 50,
        1488 to 10,
        1497 to 50,
        1490 to 10,
        1491 to 20,
        1492 to 20,
        1493 to 30,
        1494 to 30,
        1495 to 40,
        1496 to 40,
        9013 to 50,
        9014 to 50,
        9015 to 10,
        95 to 10,
        109 to 30,
        1694 to 50,
        1692 to 10,
        1691 to 20,
        1690 to 20,
        1689 to 30,
        1688 to 30,
        1687 to 40,
        1686 to 40,
        1685 to 50,
        1684 to 50,
        106 to 10,
        107 to 1,
        108 to 20,
    )

    private val CATEGORY: Map<Int, AchievementCategory> = mapOf(
        91 to AchievementCategory.GENERAL,
        133 to AchievementCategory.DRAGODINDE,
        96 to AchievementCategory.DRAGODINDE,
        97 to AchievementCategory.DRAGODINDE,
        98 to AchievementCategory.DRAGODINDE,
        99 to AchievementCategory.DRAGODINDE,
        100 to AchievementCategory.DRAGODINDE,
        101 to AchievementCategory.DRAGODINDE,
        130 to AchievementCategory.DRAGODINDE,
        131 to AchievementCategory.DRAGODINDE,
        132 to AchievementCategory.DRAGODINDE,
        1488 to AchievementCategory.MULDO,
        1497 to AchievementCategory.MULDO,
        1490 to AchievementCategory.MULDO,
        1491 to AchievementCategory.MULDO,
        1492 to AchievementCategory.MULDO,
        1493 to AchievementCategory.MULDO,
        1494 to AchievementCategory.MULDO,
        1495 to AchievementCategory.MULDO,
        1496 to AchievementCategory.MULDO,
        9013 to AchievementCategory.MULDO,
        9014 to AchievementCategory.MULDO,
        9015 to AchievementCategory.VOLKORNE,
        95 to AchievementCategory.DRAGODINDE,
        109 to AchievementCategory.GENERAL,
        1694 to AchievementCategory.VOLKORNE,
        1692 to AchievementCategory.VOLKORNE,
        1691 to AchievementCategory.VOLKORNE,
        1690 to AchievementCategory.VOLKORNE,
        1689 to AchievementCategory.VOLKORNE,
        1688 to AchievementCategory.VOLKORNE,
        1687 to AchievementCategory.VOLKORNE,
        1686 to AchievementCategory.VOLKORNE,
        1685 to AchievementCategory.VOLKORNE,
        1684 to AchievementCategory.VOLKORNE,
        106 to AchievementCategory.GENERAL,
        107 to AchievementCategory.GENERAL,
        108 to AchievementCategory.GENERAL,
    )

    private val CHILDREN: Map<Int, List<Int>> = mapOf(
        91 to listOf(133, 1488, 1497, 9015, 95, 109, 1694),
        133 to listOf(96, 97, 98, 99, 100, 101, 130, 131, 132),
        1497 to listOf(1490, 1491, 1492, 1493, 1494, 1495, 1496, 9013, 9014),
        1694 to listOf(1692, 1691, 1690, 1689, 1688, 1687, 1686, 1685, 1684),
    )

    private val OBJECTIVES: Map<Int, String> = mapOf(
        177 to "De génération en génération",
        178 to "Prélèvement marin",
        179 to "Générations aquatiques",
        180 to "Prélèvement cornu",
        181 to "Ce n'est qu'un prélèvement",
        182 to "Allez on pousse !",
        18167 to "Générations V",
        168 to "Dragodinde : Deuxième génération",
        169 to "Dragodinde : Troisième génération",
        170 to "Dragodinde : Quatrième génération",
        171 to "Dragodinde : Cinquième génération",
        172 to "Dragodinde : Sixième génération",
        173 to "Dragodinde : Septième génération",
        174 to "Dragodinde : Huitième génération",
        175 to "Dragodinde : Neuvième génération",
        176 to "Dragodinde : Dixième génération",
        94 to "Dragodinde Amande et Rousse",
        95 to "Dragodinde Dorée et Rousse",
        96 to "Dragodinde Amande et Dorée",
        97 to "Dragodinde Ebène",
        98 to "Dragodinde Indigo",
        99 to "Dragodinde Indigo et Rousse",
        100 to "Dragodinde Ebène et Rousse",
        101 to "Dragodinde Amande et Indigo",
        102 to "Dragodinde Amande et Ebène",
        103 to "Dragodinde Dorée et Indigo",
        104 to "Dragodinde Dorée et Ebène",
        105 to "Dragodinde Ebène et Indigo",
        106 to "Dragodinde Pourpre",
        107 to "Dragodinde Orchidée",
        108 to "Dragodinde Pourpre et Rousse",
        109 to "Dragodinde Orchidée et Rousse",
        110 to "Dragodinde Amande et Pourpre",
        111 to "Dragodinde Amande et Orchidée",
        112 to "Dragodinde Dorée et Pourpre",
        113 to "Dragodinde Dorée et Orchidée",
        114 to "Dragodinde Indigo et Pourpre",
        115 to "Dragodinde Indigo et Orchidée",
        116 to "Dragodinde Ebène et Pourpre",
        117 to "Dragodinde Ebène et Orchidée",
        118 to "Dragodinde Orchidée et Pourpre",
        119 to "Dragodinde Ivoire",
        120 to "Dragodinde Turquoise",
        131 to "Dragodinde Ivoire et Rousse",
        132 to "Dragodinde Turquoise et Rousse",
        133 to "Dragodinde Amande et Ivoire",
        134 to "Dragodinde Amande et Turquoise",
        135 to "Dragodinde Dorée et Ivoire",
        136 to "Dragodinde Dorée et Turquoise",
        137 to "Dragodinde Indigo et Ivoire",
        138 to "Dragodinde Indigo et Turquoise",
        139 to "Dragodinde Ebène et Ivoire",
        140 to "Dragodinde Ebène et Turquoise",
        141 to "Dragodinde Ivoire et Pourpre",
        142 to "Dragodinde Turquoise et Pourpre",
        143 to "Dragodinde Ivoire et Orchidée",
        144 to "Dragodinde Turquoise et Orchidée",
        145 to "Dragodinde Ivoire et Turquoise",
        146 to "Dragodinde Emeraude",
        147 to "Dragodinde Prune",
        148 to "Dragodinde Emeraude et Rousse",
        149 to "Dragodinde Prune et Rousse",
        150 to "Dragodinde Amande et Emeraude",
        151 to "Dragodinde Prune et Amande",
        152 to "Dragodinde Dorée et Emeraude",
        153 to "Dragodinde Prune et Dorée",
        154 to "Dragodinde Emeraude et Indigo",
        155 to "Dragodinde Prune et Indigo",
        156 to "Dragodinde Ebène et Emeraude",
        157 to "Dragodinde Prune et Ebène",
        158 to "Dragodinde Emeraude et Pourpre",
        159 to "Dragodinde Prune et Pourpre",
        160 to "Dragodinde Emeraude et Orchidée",
        161 to "Dragodinde Prune et Orchidée",
        162 to "Dragodinde Emeraude et Ivoire",
        163 to "Dragodinde Prune et Ivoire",
        164 to "Dragodinde Emeraude et Turquoise",
        165 to "Dragodinde Prune et Turquoise",
        166 to "Dragodinde Prune et Emeraude",
        4610 to "Muldo Ebène",
        4611 to "Muldo Indigo",
        4612 to "Muldo Pourpre",
        4613 to "Muldo Orchidée",
        4614 to "Muldo Doré",
        4680 to "Muldo : Deuxième génération",
        4681 to "Muldo : Troisième génération",
        4682 to "Muldo : Quatrième génération",
        4683 to "Muldo : Cinquième génération",
        4684 to "Muldo : Sixième génération",
        4685 to "Muldo : Septième génération",
        4686 to "Muldo : Huitième génération",
        18161 to "Muldo : Neuvième génération",
        18162 to "Muldo : Dixième génération",
        4620 to "Muldo Doré et Pourpre",
        4621 to "Muldo Indigo et Pourpre",
        4622 to "Muldo Ebène et Pourpre",
        4623 to "Muldo Orchidée et Pourpre",
        4624 to "Muldo Doré et Orchidée",
        4625 to "Muldo Indigo et Orchidée",
        4626 to "Muldo Ebène et Orchidée",
        4627 to "Muldo Doré et Ebène",
        4758 to "Muldo Doré et Indigo",
        4759 to "Muldo Ebène et Indigo",
        4628 to "Muldo Roux",
        4629 to "Muldo Amande",
        4630 to "Muldo Doré et Amande",
        4631 to "Muldo Ebène et Amande",
        4632 to "Muldo Indigo et Amande",
        4633 to "Muldo Orchidée et Amande",
        4634 to "Muldo Pourpre et Amande",
        4635 to "Muldo Roux et Amande",
        4636 to "Muldo Roux et Doré",
        4637 to "Muldo Roux et Ebène",
        4638 to "Muldo Roux et Indigo",
        4639 to "Muldo Roux et Orchidée",
        4640 to "Muldo Roux et Pourpre",
        4641 to "Muldo Ivoire",
        4642 to "Muldo Turquoise",
        4643 to "Muldo Pourpre et Ivoire",
        4644 to "Muldo Orchidée et Ivoire",
        4645 to "Muldo Indigo et Ivoire",
        4646 to "Muldo Ebène et Ivoire",
        4647 to "Muldo Doré et Ivoire",
        4648 to "Muldo Roux et Ivoire",
        4649 to "Muldo Amande et Ivoire",
        4650 to "Muldo Turquoise et Ivoire",
        4651 to "Muldo Turquoise et Pourpre",
        4652 to "Muldo Turquoise et Orchidée",
        4653 to "Muldo Turquoise et Indigo",
        4654 to "Muldo Turquoise et Ebène",
        4655 to "Muldo Turquoise et Roux",
        4656 to "Muldo Turquoise et Amande",
        4657 to "Muldo Turquoise et Doré",
        4658 to "Muldo Prune",
        4659 to "Muldo Emeraude",
        4660 to "Muldo Prune et Pourpre",
        4661 to "Muldo Prune et Orchidée",
        4662 to "Muldo Prune et Indigo",
        4663 to "Muldo Prune et Ebène",
        4664 to "Muldo Prune et Doré",
        4665 to "Muldo Prune et Roux",
        4666 to "Muldo Prune et Amande",
        4667 to "Muldo Prune et Ivoire",
        4668 to "Muldo Prune et Turquoise",
        4669 to "Muldo Prune et Emeraude",
        4670 to "Muldo Pourpre et Emeraude",
        4671 to "Muldo Orchidée et Emeraude",
        4672 to "Muldo Indigo et Emeraude",
        4673 to "Muldo Ebène et Emeraude",
        4674 to "Muldo Doré et Emeraude",
        4675 to "Muldo Roux et Emeraude",
        4676 to "Muldo Amande et Emeraude",
        4677 to "Muldo Ivoire et Emeraude",
        4678 to "Muldo Turquoise et Emeraude",
        18107 to "Muldo Ambre",
        18108 to "Muldo Corail",
        18109 to "Muldo Azur",
        18110 to "Muldo Aigue-marine",
        18111 to "Muldo Ambre et Doré",
        18112 to "Muldo Ambre et Ebène",
        18113 to "Muldo Ambre et Indigo",
        18114 to "Muldo Ambre et Pourpre",
        18115 to "Muldo Ambre et Orchidée",
        18116 to "Muldo Ambre et Amande",
        18117 to "Muldo Ambre et Roux",
        18118 to "Muldo Ambre et Ivoire",
        18119 to "Muldo Ambre et Turquoise",
        18120 to "Muldo Ambre et Émeraude",
        18121 to "Muldo Ambre et Prune",
        18122 to "Muldo Ambre et Corail",
        18123 to "Muldo Ambre et Azur",
        18124 to "Muldo Ambre et Aigue-marine",
        18125 to "Muldo Corail et Doré",
        18126 to "Muldo Corail et Ebène",
        18127 to "Muldo Corail et Indigo",
        18128 to "Muldo Corail et Pourpre",
        18129 to "Muldo Corail et Orchidée",
        18130 to "Muldo Corail et Amande",
        18131 to "Muldo Corail et Roux",
        18132 to "Muldo Corail et Ivoire",
        18133 to "Muldo Corail et Turquoise",
        18134 to "Muldo Corail et Émeraude",
        18135 to "Muldo Corail et Prune",
        18136 to "Muldo Corail et Azur",
        18137 to "Muldo Corail et Aigue-marine",
        18138 to "Muldo Azur et Doré",
        18139 to "Muldo Azur et Ebène",
        18140 to "Muldo Azur et Indigo",
        18141 to "Muldo Azur et Pourpre",
        18142 to "Muldo Azur et Orchidée",
        18143 to "Muldo Azur et Amande",
        18144 to "Muldo Azur et Roux",
        18145 to "Muldo Azur et Ivoire",
        18146 to "Muldo Azur et Turquoise",
        18147 to "Muldo Azur et Émeraude",
        18148 to "Muldo Azur et Prune",
        18149 to "Muldo Azur et Aigue-marine",
        18150 to "Muldo Aigue-marine et Doré",
        18151 to "Muldo Aigue-marine et Ebène",
        18152 to "Muldo Aigue-marine et Indigo",
        18153 to "Muldo Aigue-marine et Pourpre",
        18154 to "Muldo Aigue-marine et Orchidée",
        18155 to "Muldo Aigue-marine et Amande",
        18156 to "Muldo Aigue-marine et Roux",
        18157 to "Muldo Aigue-marine et Ivoire",
        18158 to "Muldo Aigue-marine et Turquoise",
        18159 to "Muldo Aigue-marine et Émeraude",
        18160 to "Muldo Aigue-marine et Prune",
        18163 to "Volkorne Ebène",
        18164 to "Volkorne Indigo",
        18165 to "Volkorne Pourpre",
        18166 to "Volkorne Orchidée",
        72 to "Dragodinde Amande",
        73 to "Dragodinde Dorée",
        74 to "Dragodinde Rousse",
        81 to "Faire naître 1000 montures.",
        5524 to "Volkorne : Deuxième Génération",
        5525 to "Volkorne : Troisième Génération",
        5526 to "Volkorne : Quatrième Génération",
        5527 to "Volkorne : Cinquième Génération",
        5528 to "Volkorne : Sixième Génération",
        5529 to "Volkorne : Septième Génération",
        5530 to "Volkorne : Huitième Génération",
        5531 to "Volkorne : Neuvième Génération",
        5532 to "Volkorne : Dixième Génération",
        5513 to "Volkorne Pourpre et Orchidée",
        5514 to "Volkorne Pourpre et Indigo",
        5515 to "Volkorne Pourpre et Ebène",
        5516 to "Volkorne Orchidée et Indigo",
        5517 to "Volkorne Orchidée et Ebène",
        5518 to "Volkorne Indigo et Ebène",
        5509 to "Volkorne Roux",
        5510 to "Volkorne Amande",
        5511 to "Volkorne Ivoire",
        5512 to "Volkorne Turquoise",
        5487 to "Volkorne Amande et Pourpre",
        5488 to "Volkorne Amande et Orchidée",
        5489 to "Volkorne Amande et Indigo",
        5490 to "Volkorne Amande et Ebène",
        5491 to "Volkorne Amande et Roux",
        5492 to "Volkorne Amande et Ivoire",
        5493 to "Volkorne Amande et Turquoise",
        5494 to "Volkorne Roux et Pourpre",
        5495 to "Volkorne Roux et Orchidée",
        5496 to "Volkorne Roux et Indigo",
        5497 to "Volkorne Roux et Ebène",
        5498 to "Volkorne Roux et Ivoire",
        5499 to "Volkorne Roux et Turquoise",
        5500 to "Volkorne Ivoire et Pourpre",
        5501 to "Volkorne Ivoire et Orchidée",
        5502 to "Volkorne Ivoire et Indigo",
        5503 to "Volkorne Ivoire et Ebène",
        5504 to "Volkorne Ivoire et Turquoise",
        5505 to "Volkorne Turquoise et Pourpre",
        5506 to "Volkorne Turquoise et Orchidée",
        5507 to "Volkorne Turquoise et Indigo",
        5508 to "Volkorne Turquoise et Ebène",
        5485 to "Volkorne Prune",
        5486 to "Volkorne Emeraude",
        5468 to "Volkorne Prune et Pourpre",
        5469 to "Volkorne Prune et Orchidée",
        5470 to "Volkorne Prune et Indigo",
        5471 to "Volkorne Prune et Ebène",
        5472 to "Volkorne Prune et Amande",
        5473 to "Volkorne Prune et Roux",
        5474 to "Volkorne Prune et Ivoire",
        5475 to "Volkorne Prune et Turquoise",
        5476 to "Volkorne Prune et Emeraude",
        5477 to "Volkorne Emeraude et Pourpre",
        5478 to "Volkorne Emeraude et Orchidée",
        5479 to "Volkorne Emeraude et Indigo",
        5480 to "Volkorne Emeraude et Ebène",
        5481 to "Volkorne Emeraude et Amande",
        5482 to "Volkorne Emeraude et Roux",
        5483 to "Volkorne Emeraude et Ivoire",
        5484 to "Volkorne Emeraude et Turquoise",
        5467 to "Volkorne Doré",
        5457 to "Volkorne Doré et Pourpre",
        5458 to "Volkorne Doré et Orchidée",
        5459 to "Volkorne Doré et Indigo",
        5460 to "Volkorne Doré et Ebène",
        5461 to "Volkorne Doré et Roux",
        5462 to "Volkorne Doré et Amande",
        5463 to "Volkorne Doré et Ivoire",
        5464 to "Volkorne Doré et Turquoise",
        5465 to "Volkorne Doré et Prune",
        5466 to "Volkorne Doré et Emeraude",
        5453 to "Volkorne Jade",
        5454 to "Volkorne Rubis",
        5455 to "Volkorne Saphir",
        5456 to "Volkorne Améthyste",
        5403 to "Volkorne Jade et Pourpre",
        5404 to "Volkorne Jade et Orchidée",
        5405 to "Volkorne Jade et Indigo",
        5406 to "Volkorne Jade et Ebène",
        5407 to "Volkorne Jade et Amande",
        5408 to "Volkorne Jade et Roux",
        5409 to "Volkorne Jade et Ivoire",
        5410 to "Volkorne Jade et Turquoise",
        5411 to "Volkorne Jade et Prune",
        5412 to "Volkorne Jade et Emeraude",
        5413 to "Volkorne Jade et Doré",
        5414 to "Volkorne Jade et Rubis",
        5415 to "Volkorne Jade et Saphir",
        5416 to "Volkorne Jade et Améthyste",
        5417 to "Volkorne Rubis et Pourpre",
        5418 to "Volkorne Rubis et Orchidée",
        5419 to "Volkorne Rubis et Indigo",
        5420 to "Volkorne Rubis et Ebène",
        5421 to "Volkorne Rubis et Amande",
        5422 to "Volkorne Rubis et Roux",
        5423 to "Volkorne Rubis et Ivoire",
        5424 to "Volkorne Rubis et Turquoise",
        5425 to "Volkorne Rubis et Prune",
        5426 to "Volkorne Rubis et Emeraude",
        5427 to "Volkorne Rubis et Doré",
        5428 to "Volkorne Rubis et Saphir",
        5429 to "Volkorne Rubis et Améthyste",
        5430 to "Volkorne Saphir et Pourpre",
        5431 to "Volkorne Saphir et Orchidée",
        5432 to "Volkorne Saphir et Indigo",
        5433 to "Volkorne Saphir et Ebène",
        5434 to "Volkorne Saphir et Amande",
        5435 to "Volkorne Saphir et Roux",
        5436 to "Volkorne Saphir et Ivoire",
        5437 to "Volkorne Saphir et Turquoise",
        5438 to "Volkorne Saphir et Prune",
        5439 to "Volkorne Saphir et Emeraude",
        5440 to "Volkorne Saphir et Doré",
        5441 to "Volkorne Saphir et Améthyste",
        5442 to "Volkorne Améthyste et Pourpre",
        5443 to "Volkorne Améthyste et Orchidée",
        5444 to "Volkorne Améthyste et Indigo",
        5445 to "Volkorne Améthyste et Ebène",
        5446 to "Volkorne Améthyste et Amande",
        5447 to "Volkorne Améthyste et Roux",
        5448 to "Volkorne Améthyste et Ivoire",
        5449 to "Volkorne Améthyste et Turquoise",
        5450 to "Volkorne Améthyste et Prune",
        5451 to "Volkorne Améthyste et Emeraude",
        5452 to "Volkorne Améthyste et Doré",
        78 to "Faire naître 10 montures.",
        80 to "Faire naître 100 montures.",
    )
}
